/*
 */
package metricconversion;

/**
 *
 * @author c.bahsler
 */
public class Conversion extends javax.swing.JFrame {

    /**
     * Creates new form Conversion
     */
    public Conversion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        inCm = new javax.swing.JButton();
        ftCM = new javax.swing.JButton();
        ydsM = new javax.swing.JButton();
        cmFt = new javax.swing.JButton();
        mYds = new javax.swing.JButton();
        cmIn = new javax.swing.JButton();
        kmMiles = new javax.swing.JButton();
        miKm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setName("ConversionChoice"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(20, 10, 280, 80);

        inCm.setText("Inches to Centimeters");
        getContentPane().add(inCm);
        inCm.setBounds(20, 120, 280, 40);

        ftCM.setText("Feet to centimeters");
        getContentPane().add(ftCM);
        ftCM.setBounds(20, 170, 280, 40);

        ydsM.setText("Yards to meters");
        getContentPane().add(ydsM);
        ydsM.setBounds(20, 220, 280, 40);

        cmFt.setText("Centimeters to feet");
        getContentPane().add(cmFt);
        cmFt.setBounds(20, 370, 280, 40);

        mYds.setText("Meters to Yards");
        getContentPane().add(mYds);
        mYds.setBounds(20, 420, 280, 40);

        cmIn.setText("Centimeters to Inches");
        getContentPane().add(cmIn);
        cmIn.setBounds(20, 320, 280, 40);

        kmMiles.setText("Kilometers to miles");
        getContentPane().add(kmMiles);
        kmMiles.setBounds(20, 470, 280, 40);

        miKm.setText("Miles to Kilometers");
        miKm.setActionCommand("Miles to Kilometers");
        getContentPane().add(miKm);
        miKm.setBounds(20, 270, 280, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmFt;
    private javax.swing.JButton cmIn;
    private javax.swing.JButton ftCM;
    private javax.swing.JButton inCm;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton kmMiles;
    private javax.swing.JButton mYds;
    private javax.swing.JButton miKm;
    private javax.swing.JButton ydsM;
    // End of variables declaration//GEN-END:variables
}
