package showdowngame;

import javax.swing.JLabel;

/**
 *
 * @author Chelsea Bahsler <your.name at your.org> ;
 */
public class UserInterface extends javax.swing.JFrame {

    private Engine engine;
    /**
     * Creates new form UserInterface1
     */
    public UserInterface() {
        initComponents();
        // The three hero lives
        JLabel[] heroLives = {
            LifeHero1, LifeHero2, LifeHero3
        };

        // The two villain lvies
        JLabel[] villainLives = {
            LifeVillain1, LifeVillain2
        };

        // The wall labels
        JLabel[] walls = {
            wallVillain, wallVerticalL, wallVerticalR,
            wallCentre, wallBottom, wallTop
        };

        // the two walls colored the same as the background
        JLabel[] villainBounceWalls = {
            villainWall, villainWallR
        };

        // The zone labels
        JLabel[] hitZones = {
            HitzoneR, HitzoneL
        };

        // Items called from the Engine class
        engine = new Engine(hero, villain, Description, Background,
                heroLives, villainLives,
                walls, villainBounceWalls,
                hitZones, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallVerticalL = new javax.swing.JLabel();
        wallTop = new javax.swing.JLabel();
        wallBottom = new javax.swing.JLabel();
        wallCentre = new javax.swing.JLabel();
        wallVerticalR = new javax.swing.JLabel();
        villainWallR = new javax.swing.JLabel();
        villainWall = new javax.swing.JLabel();
        wallVillain = new javax.swing.JLabel();
        villain = new javax.swing.JLabel();
        hero = new javax.swing.JLabel();
        HitzoneR = new javax.swing.JLabel();
        HitzoneL = new javax.swing.JLabel();
        titleDarkShowdown2 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        VillainLivesText = new javax.swing.JLabel();
        LifeVillain1 = new javax.swing.JLabel();
        LifeVillain2 = new javax.swing.JLabel();
        LivesHeroText = new javax.swing.JLabel();
        LifeHero1 = new javax.swing.JLabel();
        LifeHero2 = new javax.swing.JLabel();
        LifeHero3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        wallVerticalL.setBackground(new java.awt.Color(0, 0, 0));
        wallVerticalL.setText("Wall");
        wallVerticalL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallVerticalL.setOpaque(true);
        getContentPane().add(wallVerticalL);
        wallVerticalL.setBounds(0, 10, 10, 530);

        wallTop.setBackground(new java.awt.Color(0, 0, 0));
        wallTop.setText("Wall");
        wallTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallTop.setOpaque(true);
        getContentPane().add(wallTop);
        wallTop.setBounds(0, 0, 800, 10);

        wallBottom.setBackground(new java.awt.Color(0, 0, 0));
        wallBottom.setText("Wall");
        wallBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallBottom.setOpaque(true);
        getContentPane().add(wallBottom);
        wallBottom.setBounds(0, 500, 800, 20);

        wallCentre.setBackground(new java.awt.Color(0, 0, 0));
        wallCentre.setText("Wall");
        wallCentre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallCentre.setOpaque(true);
        getContentPane().add(wallCentre);
        wallCentre.setBounds(0, 250, 800, 10);

        wallVerticalR.setBackground(new java.awt.Color(0, 0, 0));
        wallVerticalR.setText("Wall");
        wallVerticalR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallVerticalR.setOpaque(true);
        getContentPane().add(wallVerticalR);
        wallVerticalR.setBounds(790, 0, 10, 530);

        villainWallR.setText("villainPath");
        villainWallR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(villainWallR);
        villainWallR.setBounds(730, 20, 20, 70);

        villainWall.setText("villainPath");
        villainWall.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(villainWall);
        villainWall.setBounds(90, 20, 20, 60);

        wallVillain.setBackground(new java.awt.Color(0, 0, 0));
        wallVillain.setText("Wall");
        wallVillain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wallVillain.setOpaque(true);
        getContentPane().add(wallVillain);
        wallVillain.setBounds(370, 90, 100, 10);

        villain.setBackground(new java.awt.Color(204, 0, 0));
        villain.setForeground(new java.awt.Color(255, 255, 255));
        villain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        villain.setText("Villain");
        villain.setToolTipText("");
        villain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        villain.setOpaque(true);
        getContentPane().add(villain);
        villain.setBounds(400, 30, 40, 40);

        hero.setBackground(new java.awt.Color(0, 153, 153));
        hero.setForeground(new java.awt.Color(255, 255, 255));
        hero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hero.setText("Hero");
        hero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hero.setOpaque(true);
        getContentPane().add(hero);
        hero.setBounds(400, 440, 40, 40);

        HitzoneR.setText("Hitzone Right");
        HitzoneR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        HitzoneR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        HitzoneR.setFocusable(false);
        getContentPane().add(HitzoneR);
        HitzoneR.setBounds(470, 0, 260, 500);

        HitzoneL.setForeground(new java.awt.Color(255, 255, 255));
        HitzoneL.setText("Hitzone Left");
        HitzoneL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        HitzoneL.setFocusable(false);
        getContentPane().add(HitzoneL);
        HitzoneL.setBounds(110, 0, 260, 500);

        titleDarkShowdown2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        titleDarkShowdown2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDarkShowdown2.setText("SHOWDOWN");
        getContentPane().add(titleDarkShowdown2);
        titleDarkShowdown2.setBounds(800, 10, 200, 40);

        Description.setBackground(new java.awt.Color(204, 204, 204));
        Description.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        Description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Description.setToolTipText("");
        Description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Description.setName("Description"); // NOI18N
        getContentPane().add(Description);
        Description.setBounds(810, 40, 180, 230);

        VillainLivesText.setBackground(new java.awt.Color(204, 0, 0));
        VillainLivesText.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        VillainLivesText.setForeground(new java.awt.Color(255, 255, 255));
        VillainLivesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VillainLivesText.setText("Villain Lives");
        VillainLivesText.setToolTipText("");
        VillainLivesText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VillainLivesText.setName("LivesText"); // NOI18N
        VillainLivesText.setOpaque(true);
        getContentPane().add(VillainLivesText);
        VillainLivesText.setBounds(810, 320, 180, 30);

        LifeVillain1.setBackground(new java.awt.Color(204, 0, 0));
        LifeVillain1.setForeground(new java.awt.Color(255, 255, 255));
        LifeVillain1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LifeVillain1.setText("1");
        LifeVillain1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LifeVillain1.setOpaque(true);
        getContentPane().add(LifeVillain1);
        LifeVillain1.setBounds(810, 360, 80, 40);

        LifeVillain2.setBackground(new java.awt.Color(204, 0, 0));
        LifeVillain2.setForeground(new java.awt.Color(255, 255, 255));
        LifeVillain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LifeVillain2.setText("2");
        LifeVillain2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LifeVillain2.setOpaque(true);
        getContentPane().add(LifeVillain2);
        LifeVillain2.setBounds(910, 360, 80, 40);

        LivesHeroText.setBackground(new java.awt.Color(0, 153, 153));
        LivesHeroText.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        LivesHeroText.setForeground(new java.awt.Color(255, 255, 255));
        LivesHeroText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LivesHeroText.setText("Lives");
        LivesHeroText.setToolTipText("");
        LivesHeroText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LivesHeroText.setName("LivesText"); // NOI18N
        LivesHeroText.setOpaque(true);
        getContentPane().add(LivesHeroText);
        LivesHeroText.setBounds(810, 410, 180, 30);

        LifeHero1.setBackground(new java.awt.Color(0, 153, 153));
        LifeHero1.setForeground(new java.awt.Color(255, 255, 255));
        LifeHero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LifeHero1.setText("1");
        LifeHero1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LifeHero1.setOpaque(true);
        getContentPane().add(LifeHero1);
        LifeHero1.setBounds(810, 450, 40, 40);

        LifeHero2.setBackground(new java.awt.Color(0, 153, 153));
        LifeHero2.setForeground(new java.awt.Color(255, 255, 255));
        LifeHero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LifeHero2.setText("2");
        LifeHero2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LifeHero2.setOpaque(true);
        getContentPane().add(LifeHero2);
        LifeHero2.setBounds(880, 450, 40, 40);

        LifeHero3.setBackground(new java.awt.Color(0, 153, 153));
        LifeHero3.setForeground(new java.awt.Color(255, 255, 255));
        LifeHero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LifeHero3.setText("3");
        LifeHero3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LifeHero3.setOpaque(true);
        getContentPane().add(LifeHero3);
        LifeHero3.setBounds(950, 450, 40, 40);

        Background.setBackground(java.awt.Color.lightGray);
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Background.setOpaque(true);
        getContentPane().add(Background);
        Background.setBounds(0, -10, 800, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        engine.keypress(evt);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel HitzoneL;
    private javax.swing.JLabel HitzoneR;
    private javax.swing.JLabel LifeHero1;
    private javax.swing.JLabel LifeHero2;
    private javax.swing.JLabel LifeHero3;
    private javax.swing.JLabel LifeVillain1;
    private javax.swing.JLabel LifeVillain2;
    private javax.swing.JLabel LivesHeroText;
    private javax.swing.JLabel VillainLivesText;
    private javax.swing.JLabel hero;
    private javax.swing.JLabel titleDarkShowdown2;
    private javax.swing.JLabel villain;
    private javax.swing.JLabel villainWall;
    private javax.swing.JLabel villainWallR;
    private javax.swing.JLabel wallBottom;
    private javax.swing.JLabel wallCentre;
    private javax.swing.JLabel wallTop;
    private javax.swing.JLabel wallVerticalL;
    private javax.swing.JLabel wallVerticalR;
    private javax.swing.JLabel wallVillain;
    // End of variables declaration//GEN-END:variables
}
